- name: Install docker & requirements
  hosts: web
  become: yes  # utiliser sudo
  roles:
    - role: install_docker
  vars_files:
    - vars/vars_docker_install.yml
    - vars/vars_compose.yml
  tasks:
    - name: Start docker
      systemd:
        name: docker
        state: started
        enabled: yes
      
    - name: Create required directories
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - /home/hkrifa/data
        - /home/hkrifa/data/wordpress
        - /home/hkrifa/data/mysql
        - /home/hkrifa/data/phpmyadmin
        - /home/hkrifa/app
        - /home/hkrifa/app/src
    
    - name: Generate self-signed certificate
      ansible.builtin.command:
        cmd: openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/nginx.key -out /etc/ssl/certs/nginx.crt -subj "/C=FR/ST=Nice/L=Nice/O=42nice/OU=hkrifa/CN=51.158.118.190"
      
    # - name: Generate nginx config
    #   template:
    #     src: nginx-conf/nginx.conf.j2
    #     dest: /home/hkrifa/app/nginx.conf

    - name: Generate docker-compose.yml
      template:
        src: docker-compose/docker-compose.yml.j2
        dest: /home/hkrifa/app/docker-compose.yml