# Stop Containers
- name: Stop docker-compose
  hosts: web
  become: yes
  vars_files:
    - vars/vars_compose.yml
  tasks:
    - name: Stop containers
      community.docker.docker_compose:
        project_src: /home/hkrifa/app
        state: absent